### ISSUE TITLE
reactie op publieke consultatie mijnbouwwetvergunning  ikv BRO

### ISSUE THREAD

**Issue by AvDKWR** [BROprogramma/EPL#10]
REACTIE op publieke consultatie mijnbouwwetvergunning ikv BRO

Eerste vraag is “wat is het doel van dit registratieobject?”
Dàt er een vergunning is of komt die interfereert met een drinkwaterwinning is iets dat ook uit de Staatscourant zou moeten blijken. Wat bij me opkomt is of die publicatieroute blijft bestaan of dat we in de toekomst zelf continu allerlei Basisregistraties moeten scannen. Wordt de BRO onderdeel van een piepsysteem?

Vervolgens:
De insteek zou verder kunnen of moeten zijn (vanuit herbruikbaarheid) dat er voldoende informatie in dat registratieobject komt om bijvoorbeeld het volgende te achterhalen:
•        Waar (voor welk gebied) spelen dan wel speelden MBW-vergunningen?
•        Wat voor soort informatie (inhoudelijke / bestuurlijke / technische etc. info) is er bij die vergunningaanvragen en –verleningen gebruikt die bij een andere vergunningprocedure opnieuw in stelling zou kunnen worden gebracht?

Interessant is dan wat expliciet NIET wordt vastgelegd. (Hebben we überhaupt invloed op wat er wel en niet in de BRO komt?)
•        Winning- en opslagplannen. De methode waarop wordt gewonnen / opgeslagen lijkt me nogal van invloed op risico’s voor grondwatervoorraden.
•        IMBRO/A  “De definitie van de gegevens voor het kwaliteitsregime IMBRO/A ontbreekt.” Lijkt me een cruciaal iets; we hebben ook met lopende vergunningen van doen, daarvan moeten we voldoende goed kunnen achterhalen hoe die in elkaar zitten.
•        Bij het proces van verlenen van vergunningen, i.h.b. bezwaren/zienswijzen, lijkt het me interessant om de argumentatie later te kunnen naslaan.
•        Kennelijk is het plan om alleen vergunde activiteiten in de BRO op te nemen. Ik denk dat het juist heel erg relevant is om ook informatie over (1) lopende aanvragen en (2) afgewezen vergunningen in te kunnen zien.
(1)    Lopende aanvragen lijkt me evident – hoe komen we (buiten jaargangen Staatscouranten doorpluizen) er anders achter? Vergelijk: In mijn woonbuurt in A’dam kan ik via de gemeente op basis van mijn postcode er zó achter komen wat er allemaal rond mijn huis speelt zodat ik tijdig een zienswijze kan indienen. Zoiets zou ook voor de vergunnings-registratie-objecten in de BRO moeten gelden.
(2)    Afgewezen – wat zijn de afwegingen geweest? die afwegingen kunnen nl. heel goed herbruikbaar zijn.

(1)    “Geometrie van een vergunning”  Activiteiten op grote diepte buiten de beschermingsgebieden sensu lato, kunnen ook invloed kunnen hebben op grondwaterwinningen en – voorraden binnen beschermingsgebieden. Eigenlijk is er nu niemand (behalve provincies vanuit KRW en bescherming van grondwatervoorraden) die belang heeft bij grondwatervoorraden buiten beschermingsgebieden, terwijl je zou kunnen bedenken dat die voorraden in de toekomst wel degelijk nodig zouden kunnen zijn. Geldt ook voor brak grondwater.
Denk aan:
•        Langzame grondwaterstroming en convectie binnen een wvp door opwarming van grondwater langs een heet boorgat. Zolang die activiteiten buiten beschermingsgebieden liggen kunnen we formeel niet veel.
•        Gedevieerd boren – dan kan het voorkomen dat i.g.v. een concessie buiten een grw.beschermingsgebied de feitelijke “win  of opslaglocatie”.wel degelijk recht onder dat grw.beschermingsgebied ligt. Het punt is (weer) analoog aan dat een 2D beschermingszone zoals we die kennen van grondwaterwinningen niet altijd even adequaat uitvalt.

(2)    Wordt in de BRO ook iets opgenomen over hoe monitoring van effecten van vergunde activiteiten is geregeld? Zie bijv. de recente ontdekking dat er jarenlang een lekkage was in de omgeving van Rossum (NAM) – zie 29 augustus 2017, Tubantia, beschikbaar op: http://www.tubantia.nl/dinkelland/ernstige-bodemverontreiniging-op-nam-locatie-in-rossum~a14c3af0/ 
Over lekkages zijn ook Kamervragen gesteld. Worden de bodem, de diepe ondergrond en het grondwater gemonitord bij mijnbouwactiviteiten om lekkages op te merken?  
Ook hier geldt weer dat diepe locaties recht BUITEN een grw.beschermingsgebied via lateraal lekken (langs openstaande (rek)breuken bijv.) ook in zo’n beschermingsgebied zouden kunnen komen.

(3)    T.a.v. 2.1 Reikwijdte m.b.t. mijnbouwactiviteiten: wellicht hier ook opnemen dat er gebieden zijn waar mijnbouwactiviteiten niet mogen plaatsvinden, zoals Natura2000 gebieden en beschermingszones voor drinkwaterbronnen.

(4)    Indien de mijnbouwvergunning wordt verleend voor een bepaalde tijd, hoe ziet de nazorg er uit opdat geen ongewenste emissies kunnen optreden nadat de mijnbouwactiviteiten zijn gestopt? Hierover zou iets opgenomen kunnen worden na reden beëindiging (pagina 27).

(5)    In het document staat geen enkele verwijzing naar de SodM  dat is toch de verantwoordelijke instantie voor dit soort activiteiten. In ieder geval bij calamiteiten zal de SodM moeten worden ingelicht.

**Comment by dloeve** [comment]
**Achtegrond**
Er zijn 11 basisregistraties. Een basisregistratie is een door de overheid officieel aangewezen registratie met gegevens die door alle overheidsinstellingen verplicht worden gebruikt bij de uitvoering van publiekrechtelijke taken. Dit kan gaan om uitrukkende hulpdiensten, het efficiënt vaststellen van het recht op uitkering of het toetsen van vergunningaanvragen. De BRO is de 12e basisregistratie en gaan  gegevens bevatten over geologische en bodemkundige opbouw  en, voor zover van belang voor het benutten van natuurlijke hulpbronnen in de ondergrond, ondergrondse constructies  en gebruiksrechten.  Overheidsorganen zijn verplicht deze data te gebruiken via webservices, een centrale website en publieke dienstverlening op de kaart (PDOK) zal dit worden ontsloten.

**Vraag 1:** Wat is het doel van dit registratieobject?    
Antwoord: Het registeren van de essentie van een vergunning, uiteraard zal   deze informatie via de Staatscourant gepubliceerd worden en te vinden zijn,   echter door de essentie te registreren is dat niet meer nodig en is alle   relevante informatie over een MB vergunning te vinden in de BRO onder het   registratieobject mijnbouwvergunningen. Daaruit volgt dan ook dat men   overheidsorganen kan verplichten de BRO te gebruiken (eenmalige inwinning,   meervoudig gebruik).
**Vraag 2**: Waar spelen dan wel speelden de MBW   vergunningen? 
 Antwoord: Uiteraard worden de geografische grenzen van vergunningen   geregistreerd en ook de veranderingen (geschiedenis) worden bijgehouden
**Vraag 3:** Wat voor soort informatie (inhoudelijke / bestuurlijke   / technische etc. info) is er bij die vergunningaanvragen en –verleningen   gebruikt die bij een andere vergunningprocedure opnieuw in stelling zou   kunnen worden gebracht?   
Antwoord: Het vergunningsverleningsproces en de informatie die daar bij   hoort komt niet inde BRO dit heeft te maken dat in een registratie alleen   feitelijkheden geregistreerd worden. Op het moment dat een vergunning   verleent is dan is het een feit en voldoet het aan de uitgangspunt van een   basisregistratie en zal het ook opgenomen worden in de BRO. Het is wel de   bedoeling dat het verleningsproces en de BRO goed bij elkaar aansluiten en   dat de informatie BRO (verleende vergunningen) en Niet BRO (proces van   verlening) via 1 portaal ontsloten gaat worden naar de gebruiker.
**Vraag 4:** Wat kom niet in de BRO?     
Antwoord: Winningsplannen en Opslagplannen komen niet in de BRO, het standaardiseren   van registreren is niet of nauwelijks mogelijk omdat er geen standaard format   is, echte de intentie is wel om een link op te nemen naar deze relevante   documenten.     IMBRO/A hieraan word op dit moment gewerkt en maakt nog geen onderdeel uit   van deze catalogus.     Beroep en Bezwaar van verlening komt niet in de BRO, echter als er een   wijziging plaats vind van een bestaande vergunning kan me ook in beroep en   bezwaar gaan en dit zal wel worden geregistreerd.     Het is correct dat alleen vergunde activiteiten in de BRO komen, we   onderkennen dat lopende aanvragen en afgewezen vergunningen relevante   informatie is, maar dit past niet in het uitganspunt van de BRO. De intentie   is om wel te zorgen dat deze informatie ontsloten gaat worden via 1 portaal,   ze worden echter niet in de BRO opgeslagen maar in een andere database.
**Vraag 5:** Geometrie van een vergunning?     
Antwoord: Er is geen  vraag gesteld, echter   zaken als boorgaten en putten zullen in    registratieobject MW vergunningen komen maar in registratieobject MW   putten of MW boorgaten
**Vraag 6:** Wordt in de BRO ook iets opgenomen over hoe monitoring   van effecten van vergunde activiteiten is geregeld?      
Antwoord: Dit zijn typisch zaken die in een winningsplan en opslagplan   voorkomen en die worden niet geregistreerd in de BRO reikwijdte m.b.t. mijnbouwactiviteiten: wellicht hier ook   opnemen dat er gebieden zijn waar mijnbouwactiviteiten niet mogen   plaatsvinden, zoals Natura2000 gebieden en beschermingszones voor   drinkwaterbronnen?     Antwoord: Dit is nuttige feedback en zullen kijken of we dit mee kunnen   nemen
**Vraag 7:** Indien de mijnbouwvergunning wordt verleend voor een   bepaalde tijd, hoe ziet de nazorg er uit opdat geen ongewenste emissies   kunnen optreden nadat de mijnbouwactiviteiten zijn gestopt? Hierover zou iets   opgenomen kunnen worden na reden beëindiging (pagina 27).      
Antwoord: De nazorg (o.a. ongewenste emissies) maken geen deel uit van MBW   vergunning. Om een vergunning daadwerkelijk te kunnen  beëindigen moet er eerst door het   Ministerie van EZ instemming zijn voor het sluiting- en verwijderingsplan van   mijnbouwinstallaties (indien aanwezig).    Hier kunnen nog aanvullende regels gelden bij ministeriele regeling   (bijvoorbeeld monitoring van ongewenste emissies).  Tijdens deze werkzaamheden zal SODM ook   inspecties uitvoeren. De intentie is wel om een link op te nemen naar deze   plannen
**Vraag 8:** In het document staat geen enkele verwijzing naar de   SodM?     
Antwoord: klopt SODM zijn verantwoordelijk voor meerdere zaken bij   mijnbouwwinning o.a. veiligheid. Het verlenen van een vergunning wordt   uiteindelijk door de Minister van EZ gedaan. Het registratieobject   mijnbouwwetvergunning beschrijft het recht op het uitvoeren van bepaalde   mijnbouwactiviteiten in een bepaald gebied voor een bepaalde periode. SODM is   een gebruiker van de basisregistratie. In het geval van een calamiteit zal SODM   de basisregistratie raadplegen om bijvoorbeeld te weten te komen wie de   uitvoerder is en onder welke voorwaarden de vergunning verleend is.

**Comment by IreneDeVreede-2020** [comment]
Beste AvDKWR, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
