### ISSUE TITLE
1-ste zin inleiding 

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#11]
Deze zin is niet relevant als uiteindelijk alle MBW catalogi zijn gepubliceerd, kan weg nu

**Comment by dloeve** [comment]
Dank voor je feedback, dit document is ook informerend bedoeld dus vandaar.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
