### ISSUE TITLE
Vraag 1 uit inleiding

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#13]
Liever een besluit als brondocument opnemen ipv alleen een besluitnummer en datum

**Comment by dloeve** [comment]
De bedoeling van een basisregistratie is dat het originele besluit niet meer nodig is. Alle relevante data van een besluit wordt in een basisregistratie geregistreerd met de filosofie dat deze informatie voldoende is om zonder het orginele besluit nog te moeten raadplegen. Mocht het desondanks toch nodig zijn om naar het originele besluit te gaan is dit mogelijk met besluitnummer en datum. Deze zal dus ook opgenomen worden in de BRO.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
