### ISSUE TITLE
Vraag 2 in inleiding

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#14]
Ja, het is relevant om gegevens uit opslag en winningsplannen beschikbaar te hebben in de BRO, bijvoorbeeld de contouren van verwachtte bodemdaling uit een winningsplan

**Comment by dloeve** [comment]
Dank voor de feedback, echter opslag en winningsplannen zullen niet worden gestandaardiseerd en geregistreerd worden. Wel de melding dat deze aanwezig/afwezig is met een link (dat is de intentie) naar het bestand (pdf-file)

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
