### ISSUE TITLE
Vraag 7 inleiding

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#16]
Het is wel belangrijk te weten of er sprake is van staatsdeelname, bij schade aan eigendommen dient de staat dan ook conform het aandeel te compenseren

**Comment by dloeve** [comment]
Staatsdeelname zal worden geregistreerd in de BRO, echter niet van de individuele operators

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
