### ISSUE TITLE
Pagina 8 - aanleveren historische gegevens 5 jaar na inwerkingtreding

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#17]
Hoe weet de gebruiker in welke mate de historische gegevens na die 5 jaar beschikbaar zijn in BRO? Moet de gebruiker nog in andere bronnen gaan kijken of de BRO compleet is?

**Comment by dloeve** [comment]
Niet alle gegevens zullen voldoen aan het BRO kwaliteitsregime en zullen achterblijven in DINO, bovendien vergunningen die zijn beëindigd voor 1 januari 2003 komen niet in de BRO, daar zal men andere bronnen moeten raadplegen (o.a. DINO vergunningen database).

De intentie is om dit op 1 portaal (NLOG.NL) te onsluiten zodat de gebruiker hier niks van merkt.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
