### ISSUE TITLE
pagina 8 - IMBRO/A

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#18]
Hoe zit het met vergunningen, die bestonden op 1-1-2013 en die zijn gewijzigd in de huidige versie van de MBW, blijft de gewijzigde vergunning in IMBRO/A staan? Kan een object van IMBRO/A überhaupt wijzigen naar IMBRO?

**Comment by dloeve** [comment]
- IMBRO/A geeft de conversieregels aan van het vergunningen archief in DINO naar de nieuwe BRO-standaard voor MBW vergunningen.
- IMBRO geeft aan hoe nieuwe vergunningen in de BRO komen te staan, de nieuwe gegevensdefenitie. 

Hoe gaat het nu in zijn werk: 
Eerst worden oude vergunningen naar de BRO geconverteerd met IMBRO/A conversieregels. Eenmaal een vergunning in de BRO geregistreerd, dan zal elke gebeurtenis een wijziging in de BRO opleveren volgens het IMBRO regime.  Dit is immers de nieuwe standaard in de BRO.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
