### ISSUE TITLE
pagina 9 -processen  

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#19]
waarom is er een proces van wijziging en beëindiging? Een vergunning kan gewoon aflopen zonder deze wijzigt en een vergunning kan zo worden gewijzigd dat deze is beëindigd.

**Comment by dloeve** [comment]
Proces van wijziging en beëindiging is er omdat een nieuwe gegevens door deze processen nog niet definitief zijn omdat het besluit nog niet onherroepelijk is. Er kan nog een vorm van rechtsgang zijn voordat een waarde van een attribuut definitief is. Op deze manier kan de gebruiker de 'oude waarde' voor het besluit en de nieuwe waarde vermeld in het besluit van een bepaalde entiteit/attribuut tegelijk zien. Op het moment dat het besluit onherroepelijk is zullen eventuele wijzigingen doorgevoerd worden.

Voorbeeld:
Een vergunning krijgt een nieuwe geldigheidsduur, echter er is een bezwaarprocedure gestart. Op dat moment zijn nieuwe en de oude geldigheid zichtbaar in de BRO.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
