### ISSUE TITLE
pagina 10 - reconstructie wat er vergund was

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#20]
dit kan iig alleen als de bronhouder de reeds beëindigde en nu lopende vergunningen inde BRO gaat zetten. Dit kan bij de tekst. Geldt dit ook voor verunningen onder IMBRO/A, krijgen die ook datum einde geldigheid als gegevens zijn aangepast?

**Comment by dloeve** [comment]
De IMBRO/A gegevensdefenitie is nog niet vastgesteld.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
