### ISSUE TITLE
Pagina 10 - ondersteunde processen

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#21]
Een aantal processen wordt niet ondersteunt in de BRO. Word het eindresultaat van een niet ondersteunt proces wel of niet geregistreerd, bijvoorbeeld een meetplan, sluitingsplan, winningsplan etc? Er zal de nodige behoefte zijn aan deze gegevens.

**Comment by dloeve** [comment]
Het meetplan, sluitingsplan en winningsplan word niet geregistreerd in de BRO. Voor het winningsplan zal aangeven worden of deze aanwezig is met (de intentie) een link te plaatsen naar het desbetreffende bestand (pdf file). Op dit moment wordt nog gewerkt hoe eventueel de andere data bestanden en processen op een juiste manier kunnen aansluiten op de BRO.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
