### ISSUE TITLE
pagina 11 - overschrijven oude waarden

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#22]
ik neem aan dat oude waarden bewaard blijven en dat nieuwe waarden erbij komen ipv het overschrijven van oude waarden?

**Comment by dloeve** [comment]
De groep eigenschappen waarvan de waarde in de loop van de tijd kan veranderen als gevolg van een bepaalde gebeurtenis kan in twee categorieën worden gedeeld.

De eerste categorie:
Eigenschappen waarvan voor iedere waarde de periode van geldigheid in de registratie wordt vastgelegd, worden in de basisregistratie ondergrond dynamische eigenschappen genoemd. Wanneer de waarde van een dynamische eigenschap verandert als gevolg van een bepaalde gebeurtenis, bouwt zich in de registratie ondergrond een tijdreeks op. In het domeinmodel worden de dynamische eigenschappen als een aparte categorie getoond.  
Voorbeeld: Een vergunninghouder is dynamisch gegeven, door bepaalde gebeurtenissen kan dit wijzigen, de vorige en de huidige vergunninghouder zal worden opgeslagen en op deze wijze zal een geschiedenis van verschillende vergunninghoudes  worden opgebouwd.

De tweede categorie: 
De tweede categorie omvat eigenschappen waarvan de waarde in de loop van de tijd kan veranderen maar waarvan niet voor iedere waarde de periode van geldigheid in de registratie wordt vastgelegd. Dat worden in de basisregistratie ondergrond wijzigbare eigenschappen genoemd. Wanneer de waarde van een wijzigbare eigenschap verandert als gevolg van een bepaalde gebeurtenis, bouwt zich in de registratie ondergrond geen tijdreeks op en wordt de oude waarde overschreven. In het domeinmodel worden wijzigbare eigenschappen als een aparte categorie getoond. 
Voorbeeld:
Een lopende wijziging valt in de tweede categorie en zal worden overschreven bijvoorbeeld het attribuut geldigheidsduur van een vergunning wordt d.m.v. een besluit 2 jaar langer.  De orginele waarde zal overschreven worden met de nieuwe waarde.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
