### ISSUE TITLE
Pagina 11 - definitieve verleende vergunning

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#23]
Wordt niet bedoeld dat een vergunning onherroepelijk is geworden?

**Comment by dloeve** [comment]
Nee.
Hier is echt definitief van toepassing. De terminologie die in de catalogus wordt gebruikt is als vogt: 
1. Een onherroepelijk besluit 
en een 
2. definitieve vergunning.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
