### ISSUE TITLE
Pagina 13 - correctie foutief gegeven

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#24]
Is het voor de gebruiker zichtbaar dat een foutief gegeven is gecorrigeerd? Dit is bij evaluaties/onderzoeken van belang, iemand kan beslist hebben obv een fout gegeven dat inmiddels is gecorrigeerd. Als het niet zichtbaar is kom je er niet achter op basis waarvan een beslissing is genomen

**Comment by dloeve** [comment]
Jazeker. De veranderingen worden geregistreerd in het geschiedenis domein. Dus wat en wanneer een bepaalde entiteit/attribuut is veranderd wordt geregristreerd daarnaast is ook de huidge waarde en de vorige waarde van een entiteit/attribuut beschikbaar in de BRO.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
