### ISSUE TITLE
pagina 19 - 2d vlak

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#25]
wordt dit ook niet gebruikt in de aarde, als diepte begrenzing?

**Comment by dloeve** [comment]
Nee. Het domein 2D vlak is bedoeld voor de begrenzing in het horizontale vlak en het domein dieptebereik voor het verticale vlak

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
