### ISSUE TITLE
pagona 43 - tijdgebonden verplichting uitgevoerd?

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#26]
Hoe weet je of er aan de verplichting is voldaan als de termijn is verstreken? Er is geen attribuut opgenomen '" aan verplichting voldaan"

**Comment by dloeve** [comment]
Er zijn vier tijdgebonden verplichtingen: (1) start boren voor (2) stoffen terughalen voor (3) injectieduur en (4) start injecteren voor. Men kan controleren op basis van andere registratieobjecten of hieraan voldaan is en wel de volgende: Mijnbouwwet boorgatsysteem en mijnbouwwet productiedossier. 
Voor de volledigheid het is de intentie om registratieobjecten te koppelen zodat je kunt zien onder welke vergunning er putten geboord zijn en wat en hoeveel er geproduceerd/geïnjecteerd is.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
