### ISSUE TITLE
Schaliegas

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#27]
In de catalogus wordt geen onderscheid gemaakt in schaliegas, BRO gebruikers weten niet of het een vergunning voor exploratie / winning schaliegas of conventioneel gas is. Waarom wordt dit onderscheid niet gemaakt? Dit lijkt me wel relevant

**Comment by dloeve** [comment]
In de catalogus word wel onderscheid gemaakt tussen de volgende activiteiten exploratie/winning en opslag en permanente opslag gemaakt. Op het moment dat er een (winnings)plan bekend is het pas duidelijk of het een conventioneel voorkomen is of een schaliegasvoorkomen. In een plan staat ook uit welke laag men van plan is te produceren (of op te slaan) en valt daaruit op te maken wat voor type voorkomen het gaat. Mocht er zo een conventioneel/schalie gas attribuut wenselijk zijn dan zal dit beter passen bij het registratieobject koolwaterstofvoorkomens

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
