### ISSUE TITLE
ontbreken contouren mate van bodemdaling

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#28]
In de gegevenscatalogus staat geen informatie over locatie en maximaal toegestane bodemdaling. Dit is zeer relevante informatie voor iedereen die assets heeft op het aardoppervlak om te kunnen inschatten of er hinderlijke gevolgen gaan optreden agv winning

**Comment by dloeve** [comment]
Schattingen van bodemdaling door productie is onderdeel van een winningsplan. Contouren die hierbij horen kunnen in dit document gevonden worden.  Winningsplannen worden niet gestandaardiseerd en opgenomen in de BRO, bovendien is het ook geen onderdeel van de mijnbouwvergunning. Overigens is het wel de intentie om aan te geven bij een vergunning dat een winningsplan aanwezig is en een link op te nemen naar de winningsplannen (file) zodat de waardevolle gegevens uit dit document snel gevonden kan worden

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
