### ISSUE TITLE
ontbreken van de geografische contour en diepteligging van winnings en opslag voorkomen

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#29]
In deze catalogus staat geen attributen, die de contour en diepte beschrijven van voorkomens van delfstoffen en opslag. Het gebied van een winningsvergunning is vaak een stuk groter dan het daadwerkelijke voorkomens. Via deze contouren kan er beter worden ingeschat waar evt bodemdaling gaat plaatsvinden.

**Comment by dloeve** [comment]
De contour van een voorkomen past beter in het registratieobject koolwaterstofvoorkomens. Verwachte bodemdalingsinformatie staat in de winningsplannen van een specifiek voorkomen, deze winningsplannen worden niet geregistreerd in de BRO, desondanks is het wel de intentie om een link op te nemen naar de desbetreffende winningsplannen.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
