### ISSUE TITLE
transportation

### ISSUE THREAD

**Issue by ancovdheuvel** [BROprogramma/EPL#3]
op pagina 26 wordt ingezoomd op activiteiten. In mijn beleving is transport ook een apparte activiteit omdat de kenmerken anders zijn en het risico profiel van de activiteit ook anders is. of het nu om koolwaterstoffen, CO2 en iets anders gaat.  Kern is dat de risico beheersing serieus verschuift van interne risico beheersing (meeste risico is aan de b.v win activiteit gebonden) naar externe risico beheersing (risico's van rondvarende schepen, visserij enz).

**Comment by dloeve** [comment]
Transport is een activiteit maar valt niet in de scope van de BRO (pijpleidingen vallen erbuiten)

**Comment by ancovdheuvel** [comment]
Graag even contact. Ik begrijp de antwoorden deels. Op basis van de antwoorden worstel ik met scope van het project en de scope van de verleende vergunningen. Deze zijn volgens mij niet hetzelfde en daardoor zie ik wat risico’s zie ivm opknippen. Even afstemmen of ik het goed begrijp en hoe we eventuele rest risico’s gaan beheersen.

Groet Anco van den Heuvel
0646745227




Verzonden met BlackBerry Work
(www.blackberry.com)

Van: dloeve <notifications@github.com<mailto:notifications@github.com>>
Datum: vrijdag 08 dec. 2017 3:41 PM
Aan: BROprogramma/EPL <EPL@noreply.github.com<mailto:EPL@noreply.github.com>>
Kopie: Heuvel, Anco van den (NN) <anco.vanden.heuvel@rws.nl<mailto:anco.vanden.heuvel@rws.nl>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Onderwerp: Re: [BROprogramma/EPL] transportation (#3)


Transport is een activiteit maar valt niet in de scope van de BRO (pijpleidingen vallen erbuiten)

**Comment by IreneDeVreede-2020** [comment]
Beste Anco van den Heuvel, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
