### ISSUE TITLE
Ontbreken van informatie of er een productieplafond aanwezig is

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#31]
In de catalogus staat geen attribuut, die beschrijft of er een productieplafond is en wat daarvan de omvang is

**Comment by dloeve** [comment]
Dit attribuut zal waarschijnlijk meer passen bij het registratieobject (RO) mijnbouwwetproductiedossier die bij de betreffende vergunning hoort. Deze suggestie zal meegenomen worden bij het definiëren van de catalogus van het desbetreffende RO.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
