### ISSUE TITLE
Gegevens van mijnbouwwerken ontbreken 

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#32]
gegevens zoals locatie, functie, naam eigenaar, in verbinding met.. van mijnbouwwerken zijn niet beschikbaar in deze catalogus. Komen deze belangrijke gegevens wel beschikbaar in deze of ander MBW catalogus?

**Comment by dloeve** [comment]
De infrastructuur gegevens (platform en pijpleidingen)  is geen onderdeel van de BRO op dit moment. Echter putten en boorgaten zullen wel opgeslagen worden incl. naam /eigenaar/actief etc.  Dit zal gebeuren in de registratieobjecten mijnbouwwet putsuteem en mijnbouwwet boorgatsysteem

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
