### ISSUE TITLE
(historische) gegevens van winning delfstoffen via groeven en mijnen 

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#33]
Deze gegevens ontbreken in de catalogus, waarom is dat?

**Comment by dloeve** [comment]
Deze gegevens van winning (en opslag) van olie/gas/geothermie en zout past typisch in het registratieobject (RO) Mijnbouwwwet productiedossier en zal in dit RO verder uitgewerkt worden. Daarnaast is de scope van de RO mijnbouwvergunning als volgt: vergunningen die vallen onder de mijnbouwwet per 1-1-2003. In deze wet zijn groeves en mijnen (steenkool) vervallen. De gegevens omtrent de vergunning die zijn vervallen voor 1-1-2003 zal niet worden opgenomen in de BRO.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
