### ISSUE TITLE
MBW vergunningen voor realisatie pijpleidingen, installaties ontbreken  

### ISSUE THREAD

**Issue by Rivierkundige** [BROprogramma/EPL#34]
Waarom ontbreken de MBW vergunningen tbv realisatie pijpleidingen, installaties ?

**Comment by dloeve** [comment]
Het registratieobject EPL (Exploratie en Productie License) gaat het puur en alleen om mijnbouwvergunningen die vallen onder de mijnbouwwet. Zoals in Hoofstuk 2 in meer 
detail beschreven staat beschrijft het registratieobject mijnbouwwetvergunning het recht op het uitvoeren van bepaalde mijnbouwactiviteiten in een bepaald gebied en volgt de terminologie van de mijnbouwwet die dit allemaal regelt. De activiteiten waar het over gaat zijn het opsporen van delfstoffen, aardwarmte, en CO2opslagcomplexen, het winnen van delfstoffen en aardwarmte, en het opslaan van stoffen en het permanent opslaan van CO2 in de ondergrond.Transport is inderdaad ook een activiteit maar daarvoor heeft men geen mijnbouwvergunning nodig (wel andere vergunningen uiteraard) dit zou dan bij een ander registratieobject horen. Op dit moment is het zo dat pijpleiding en ook andere manieren van transport  niet in de scope van de BRO zit en daardoor zullen ook vergunningen voor deze transport activiteiten ook niet opgenomen worden in de BRO.

**Comment by IreneDeVreede-2020** [comment]
Beste Rivierkundige, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
