### ISSUE TITLE
Vergunningen gebied

### ISSUE THREAD

**Issue by ancovdheuvel** [BROprogramma/EPL#4]
Ik lees het vergunningen gebied. Ik mis hierin de ligging van de Kabels en leidingen. Buiten de potentiele discussie lijn of vlak wil ik in eerste instantie voorstellen om een lijn te gebruiken.

Let op dit is ook essentieel omdat de meeste mijnbouw vergunningen uit 2 delen bestaan. een winnings vergunning en een deeltje transport, aanleggen, hebben, gebruiken en onderhouden van b.v. een pijpleiding.

**Comment by dloeve** [comment]
Pijpleidingen en Kabels vallen niet in de scope van de BRO. Bovendien heeft geen mijnbouwvergunning voor het aanleggen hiervan maar andere.

**Comment by IreneDeVreede-2020** [comment]
Beste Anco van den Heuvel, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
