### ISSUE TITLE
Referentie stelsel

### ISSUE THREAD

**Issue by ancovdheuvel** [BROprogramma/EPL#5]
Er wordt een vraag gesteld of iets binnen of buiten de 3 mijls zone valt. Kern hierbij is dat men zich moet realiseren dat de 3 mijls grens geen vaste lijn is maar een dynamische lijn welke door Hyrografie wordt bij gehouden. Dit is op 2 manieren op te lossen :
- door bij binnen of buiten de 3 mijls zone te referen naar een datum van de gebruikte begrenzingen;
- Door de locatie te tacken en dit veld automatisch te laten aanvullen door een generator die op basis van de actueel geldende 3 mijls zone het antwoordt genereerd.
Dit zal mogelijk niet snel een landelijk issue zijn maar dit speeld wel boven de waddeneilanden.

**Comment by dloeve** [comment]
Dank voor de feedback, bij het implementeren zal hier naar gekeken worden

**Comment by IreneDeVreede-2020** [comment]
Beste Anco van den Heuvel, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
