### ISSUE TITLE
Uitvoerder pagina 42

### ISSUE THREAD

**Issue by ancovdheuvel** [BROprogramma/EPL#6]
Hierbij moeten we duidelijk maken dat we hier te maken hebben met of:
penvoerder / de gene die regelt namens 1 of meer bedrijven  of het bedrijf dat realiseerd/uitvoerd (dus een aannemer). dit wordt uit de tekst niet duidelijk wat er nu precies bedoeld wordt. 
Als het en en is dient dit topic meerder velden te hebben.

**Comment by dloeve** [comment]
De uitvoerder is het aanspreekpunt voor het ministerie van economische zaken en staatstoezicht op de mijnen voor een bepaalde vergunning namens alle vergunninghouders.

**Comment by IreneDeVreede-2020** [comment]
Beste Anco van den Heuvel, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
