### ISSUE TITLE
9 tijdgebonden verplichtingen

### ISSUE THREAD

**Issue by ancovdheuvel** [BROprogramma/EPL#7]
niet alleen het onttrekken van plaatsen van stoffen zijn tijdsgebonden verplichtingen ook het opruimen van infrastructuur als dit niet meer nodig is. Dit geldt dus ook voor kabels en leidingen en platforms.

**Comment by dloeve** [comment]
Klopt helemaal dat dit ook verplichtingen zijn, maar dat hoort niet bij een MBW vergunning, dit is onderdeel van andere vergunningen behorende bij die infrastructuur

**Comment by IreneDeVreede-2020** [comment]
Beste Anco van den Heuvel, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
