### ISSUE TITLE
Diepte

### ISSUE THREAD

**Issue by ancovdheuvel** [BROprogramma/EPL#8]
Ik lees in de stukken niet welke referentie vlak gebruikt wordt voor de diepte. Is dit NAP, LAT of nog weer een ander referentie vlak. dit is van belang omdat het snel een meter of meer scheelt voor minder diepe vergunniningen is dit het verschil tussen iets aan de oppervlakte van de waterbodem hebben liggen of veilig en diep genoeg zijn ingegraven.

**Comment by dloeve** [comment]
Bij de begrenzing van de diepte in meters gaat het om een globale diepte. Op zee wordt de diepte gegeven t.o.v. MSL (Mean Sea Level), op land ten opzichte van NAP (Normaal Amsterdams Peil).

**Comment by IreneDeVreede-2020** [comment]
Beste Anco van den Heuvel, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
