### ISSUE TITLE
Opname vergunningen in BRO-EPL

### ISSUE THREAD

**Issue by TNOhollenahm** [BROprogramma/EPL#9]
pagina 8: "De Mijnbouwwet is op 1 januari 2003 in werking getreden en is sindsdien meermalen gewijzigd. Alle vergunningen die op 1 januari 2003 bestonden en op die datum niet beëindigd waren, worden in de basisregistratie ondergrond opgenomen."

[ En dan natuurlijk ook de vergunningen die na 1-1-2003 verleend zijn ("op" vervangen door "vanaf"?) ]
Er bestaan 2 gegevensbestanden voor Mijnbouwvergunningen: MIJNIS (MinEZ, afgesloten) en DINO-LIC (TNO, levend). Bij het opstarten van deze gegevensbestanden zijn de toen de geldige vergunningen opgenomen. MIJNIS en DINO-LIC overlappen deels.
Maar er hebben daarbuiten meer vergunningen voor opsporing en winning bestaan.

Ik zou liefst graag een volledig gegevensbestand zien, vanaf het begin van de exploratie en winning tot de huidige tijd.

**Comment by dloeve** [comment]
De scope van de BRO is zoals beschreven op pagina 8, en daar passen eerdere vergunningen niet bij. De rationale is dat hergebruik van deze vergunningen minimaal is en daardoor onnodig. Uiteraard zijn er specialisten die hier toch in geïnteresseerd zijn en deze zullen dan andere bronnen dan de BRO moeten gebruiken om deze data te raadplegen.

**Comment by IreneDeVreede-2020** [comment]
Beste TNOhollenahm, 

Nogmaals dank voor het indienen van uw vragen en of opmerkingen in de publieke consultatie van het registratieobject Mijnbouwwetvergunningen in 2017. Deze versie van de catalogus is uiteindelijk niet in werking gegaan. 

Dit issue wordt daarom gesloten.

U bent uitgenodigd om via onderstaande link te reageren op de consultatie van de nieuwe catalogus, deze loopt van 1 februari tot 15 maart.
https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/publieke-consultaties/publieke-consultatie-mijnbouwwetvergunning/

Met vriendelijke groet,
Het BRO standaardisatie team
